# Generated by Django 3.2 on 2021-05-01 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210501_2241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
