# Generated by Django 3.2 on 2021-05-03 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userrole_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
    ]
