# Generated by Django 3.2 on 2021-05-01 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyConfirmEmail',
        ),
    ]
