# Generated by Django 3.2 on 2021-05-04 06:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210504_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headquarter', models.CharField(max_length=120)),
                ('subquarter', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companydetail')),
            ],
        ),
    ]
