# Generated by Django 3.2 on 2021-05-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20210504_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarters',
            name='subquarter',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
