# Generated by Django 3.2 on 2021-05-04 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_quarters_subquarter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quarters',
            new_name='Quarter',
        ),
    ]
