# Generated by Django 3.2 on 2021-04-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_applicantinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicantInfo',
            new_name='ApplicantDetails',
        ),
    ]
