# Generated by Django 3.2 on 2021-04-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_auto_20210413_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetails',
            name='about',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='achievements',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='interest',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetails',
            name='qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
