# Generated by Django 3.2 on 2021-04-13 16:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicant', '0006_auto_20210413_1957'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicantDetails',
            new_name='ApplicantDetail',
        ),
    ]
