# Generated by Django 3.2 on 2021-04-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0007_rename_applicantdetails_applicantdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetail',
            name='about',
            field=models.TextField(blank=True, default='about', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetail',
            name='achievements',
            field=models.CharField(blank=True, default='achievements', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetail',
            name='first_name',
            field=models.CharField(blank=True, default='first_name', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetail',
            name='interest',
            field=models.CharField(blank=True, default='interest', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetail',
            name='last_name',
            field=models.CharField(blank=True, default='last_name', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='applicantdetail',
            name='qualification',
            field=models.CharField(blank=True, default='qualification', max_length=200, null=True),
        ),
    ]
