# Generated by Django 3.2 on 2021-04-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0009_auto_20210414_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdetail',
            name='github_username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
