# Generated by Django 3.2 on 2021-05-01 06:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicant', '0010_applicantdetail_github_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfirmEmail',
            new_name='ApplicantConfirmEmail',
        ),
    ]
